spring.datasource.url=jdbc:postgresql://localhost:5432/Travel_management
spring.datasource.username=postgres
spring.datasource.password=srimathi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true